name: nano33_ble_imu
description: A Flutter app to capture IMU data from Arduino Nano 33 BLE.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.4.0
  permission_handler: ^10.2.0
  charts_flutter: ^0.12.0
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true